server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://mysql:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true