spring:
  application:
    name: cart-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cart_db?useSSL=false&serverTimezone=Asia/Kolkata&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:adhiyan8718}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

security:
  jwt:
    issuer: multi-vendor-platform
    secret: ${JWT_SECRET:8F9D7A2C4B6E8F1D3A5C7E9B1D2F4A6C8E0F2A4B6C8D1E3F5A7B9C1D3E5F7A9}
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7