spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=Asia/Kolkata&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:adhiyan8718}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ${JWT_SECRET:8F9D7A2C4B6E8F1D3A5C7E9B1D2F4A6C8E0F2A4B6C8D1E3F5A7B9C1D3E5F7A9}

  service:
    token: ${ORDER_SERVICE_TOKEN:order-service-internal-token}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  kafka:
    topics:
      payment: ${KAFKA_PAYMENT_TOPIC:payment-events}